language: go

sudo: required

go:
  - 1.13.x

env:
  global:
    - OPERATOR_NAME=rhi-operator

stages:
  - test

jobs:
  include:
    - stage: test
      script:
        - cd $HOME/gopath/src/github.com/redhat-integration/$OPERATOR_NAME && make test/unit
        - go get github.com/mattn/goveralls
        - go install github.com/mattn/goveralls
        - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken=$COVERALLS_TOKEN || echo "push to coveralls failed"
